name: Generate Image List

on:
  push:
    paths:
      - 'assets/v3/**'

jobs:
  generate-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate image list
      run: |
        echo "const images = [" > assets/image-list.js
        for file in assets/v3/*; do
          echo "  '$(basename "$file")'," >> assets/image-list.js
        done
        echo "];" >> assets/image-list.js
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/image-list.js
        git commit -m "Update image list" || echo "No changes to commit"
        git push
